name = "BFAPI"
filename = "bfapi.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3561/709/bfapi.jar"
hash-format = "murmur2"
hash = "3477609411"

[update]
[update.curseforge]
file-id = 3561709
project-id = 501198
