name = "BFAPI"
filename = "bfapi.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3642/129/bfapi.jar"
hash-format = "murmur2"
hash = "76353245"

[update]
[update.curseforge]
file-id = 3642129
project-id = 501198
