name = "Fabric API"
<<<<<<< HEAD
filename = "fabric-api-0.46.0+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3605/891/fabric-api-0.46.0+1.18.jar"
hash-format = "murmur2"
hash = "4085079180"

[update]
[update.curseforge]
file-id = 3605891
=======
filename = "fabric-api-0.46.2+1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3613/749/fabric-api-0.46.2+1.18.jar"
hash-format = "murmur2"
hash = "2320157107"

[update]
[update.curseforge]
file-id = 3613749
>>>>>>> 0102699 (update tes)
project-id = 306612
