name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.6.0_MC_1.18-1.18.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3622/822/fancymenu_fabric_2.6.0_MC_1.18-1.18.1.jar"
hash-format = "murmur2"
hash = "3417986777"

[update]
[update.curseforge]
file-id = 3622822
project-id = 416796
