name = "FancyMenu [Fabric]"
filename = "fancymenu_fabric_2.5.2_MC_1.18-1.18.1.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3605/962/fancymenu_fabric_2.5.2_MC_1.18-1.18.1.jar"
hash-format = "murmur2"
hash = "466231544"

[update]
[update.curseforge]
file-id = 3605962
project-id = 416796
