name = "Iris Shaders"
<<<<<<< HEAD
filename = "iris-mc1.18.1-1.1.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3605/379/iris-mc1.18.1-1.1.5.jar"
hash-format = "murmur2"
hash = "3886317776"

[update]
[update.curseforge]
file-id = 3605379
=======
filename = "iris-mc1.18.1-1.2.0-pre.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3612/857/iris-mc1.18.1-1.2.0-pre.jar"
hash-format = "murmur2"
hash = "1505177577"

[update]
[update.curseforge]
file-id = 3612857
>>>>>>> 0102699 (update tes)
project-id = 455508

[option]
optional = true
description = "Mod de Shaders. No instalar si tienes pocos recursos"
default = true
