name = "Paintings++ (Fabric Edition)"
filename = "paintings-fabric-1.18-rc4-1.0.0.6.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3541/426/paintings-fabric-1.18-rc4-1.0.0.6.jar"
hash-format = "murmur2"
hash = "3764190262"

[update]
[update.curseforge]
file-id = 3541426
project-id = 517702
