name = "Simple Voice Chat"
filename = "voicechat-fabric-1.18.1-2.2.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3624/431/voicechat-fabric-1.18.1-2.2.13.jar"
hash-format = "murmur2"
hash = "2487941250"

[update]
[update.curseforge]
file-id = 3624431
project-id = 416089
